version: '3.8'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - net

  nest:
    image: node:latest
    container_name: nest
    restart: always
    depends_on:
      - postgres
    build: ./backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - net

volumes:
  postgres:

networks:
  net:
